provinces = {

"al" : ["alabama"],
"ak" : ["alaska"],
"az" : ["arizona"],
"ar" : ["arkansas"],
"ca" : ["california", "silicon valley", "calif"],
"co" : ["colorado"],
"ct" : ["connecticut"],
"de" : ["delaware"],
"dc" : ["district of columbia", "washington"],
"fl" : ["florida"],
"ga" : ["georgia"],
"hi" : ["hawaii",  "ni'ihau", "kaua'i", "o'ahu", "moloka'i", "lana'i", "kaho'olawe", "maui", "hawai'i"],
"id" : ["idaho"],
"il" : ["illanois"],
"in" : ["indiana"],
"ia" : ["iowa"],
"ka" : ["kansas"],
"ky" : ["kentucky"],
"la" : ["louisiana"],
"me" : ["maine"],
"md" : ["maryland"],
"ma" : ["massachusetts"],
"mi" : ["michigan"],
"mn" : ["minnesota"],
"ms" : ["mississippi"],
"mo" : ["missouri"],
"mt" : ["montana"],
"ne" : ["new england"],
"nv" : ["nevada"],
"nh" : ["new hampshire"],
"nj" : ["new jersey"],
"nm" : ["new mexico"],
"ny" : ["new york"],
"nc" : ["north carolina"],
"nd" : ["north dakota"],
"oh" : ["ohio"],
"ok" : ["oklahoma"],
"or" : ["oregon"],
"pa" : ["pennsylvania"],
"ri" : ["rhode island"],
"sc" : ["south carolina"],
"sd" : ["south dakota"],
"tn" : ["tennesee"],
"tx" : ["texas"],
"ut" : ["utah"],
"vt" : ["vermont"],
"va" : ["virginia"],
"wa" : ["washington"],
"wv" : ["west virginia"],
"wi" : ["wisconsin"],
"wy" : ["wyoming"],

"ab" : ["alberta"],
"bc" : ["british columbia"],
"mb" : ["manitoba"],
"nb" : ["new brunswick"],
"nl" : ["newfoundland", "labrador"],
"ns" : ["nova scotia"],
"nt" : ["northwest territories"],
"nu" : ["nunavut"],
"on" : ["ontario"],
"pe" : ["prince edward island", "pei"],
"qc" : ["quebec"],
"sk" : ["saskatchewan"],
"yt" : ["yukon"],

}